---
- name: Get Debian architecture
  shell: dpkg --print-architecture
  register: architecture
  changed_when: false

- name: Get Debian distribution
  shell: lsb_release -cs
  register: distribution
  changed_when: false

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present
  become: true

- name: Set up the stable repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ architecture.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ distribution.stdout }} stable"
    state: present
    update_cache: yes
  become: true

- name: Install Docker Engine
  apt:
    pkg: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
      - docker-compose
    state: present
    update_cache: yes
  become: true

- name: Add remote user to "docker" group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    group: "docker"
    append: yes
  become: true
