name: test

on:
  push:
    branches:    
      - master
  pull_request:
    branches:    
      - master

jobs:

  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    # Pull the latest image to build, and avoid caching pull-only images.
    # (docker pull is faster than caching in most cases.)
    - run: docker-compose pull

    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    # It also restores the cache if it exists.
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Build the stack
      run: docker-compose up -d --build

    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v2
      with:
        # Check the following URLs one by one sequentially
        url: http://127.0.0.1:8088/metrics|http://127.0.0.1:8087/metrics|http://127.0.0.1:8089/metrics
        # Fail this action after this many failed attempts
        max-attempts: 5
        # Delay between retries
        retry-delay: 5s
        # Retry all errors, including 404. This option might trigger curl upgrade.
        retry-all: true
        
    - name: Download dataset
      run: wget https://cdn.gorse.io/example/github.sql

    - name: Import dataset
      run: mysql -h 127.0.0.1 -u gorse -pgorse_pass gorse < github.sql
